# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Project_Elective_GUI_QT.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Elective_popupWindow_frm(object):
    def setupUi(self, Elective_popupWindow_frm):
        Elective_popupWindow_frm.setObjectName("Elective_popupWindow_frm")
        Elective_popupWindow_frm.resize(665, 492)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 97))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 97))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 97))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 97))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Elective_popupWindow_frm.setPalette(palette)
        self.Elective_greeting_lbl = QtWidgets.QLabel(Elective_popupWindow_frm)
        self.Elective_greeting_lbl.setGeometry(QtCore.QRect(160, 20, 353, 68))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.Elective_greeting_lbl.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.Elective_greeting_lbl.setFont(font)
        self.Elective_greeting_lbl.setTextFormat(QtCore.Qt.AutoText)
        self.Elective_greeting_lbl.setScaledContents(False)
        self.Elective_greeting_lbl.setObjectName("Elective_greeting_lbl")
        self.Skip_btn = QtWidgets.QPushButton(Elective_popupWindow_frm)
        self.Skip_btn.setGeometry(QtCore.QRect(80, 430, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Skip_btn.setFont(font)
        self.Skip_btn.setObjectName("Skip_btn")
        self.Continue_btn = QtWidgets.QPushButton(Elective_popupWindow_frm)
        self.Continue_btn.setGeometry(QtCore.QRect(490, 430, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Continue_btn.setFont(font)
        self.Continue_btn.setObjectName("Continue_btn")
        self.comboBox = QtWidgets.QComboBox(Elective_popupWindow_frm)
        self.comboBox.setGeometry(QtCore.QRect(80, 100, 521, 291))
        self.comboBox.setObjectName("comboBox")

        self.retranslateUi(Elective_popupWindow_frm)
        QtCore.QMetaObject.connectSlotsByName(Elective_popupWindow_frm)

    def retranslateUi(self, Elective_popupWindow_frm):
        _translate = QtCore.QCoreApplication.translate
        Elective_popupWindow_frm.setWindowTitle(_translate("Elective_popupWindow_frm", "Form"))
        self.Elective_greeting_lbl.setText(_translate("Elective_popupWindow_frm", "<html><head/><body><p align=\"center\">Choose an [Elective Title] <br/>Elective</p></body></html>"))
        self.Skip_btn.setText(_translate("Elective_popupWindow_frm", "Skip"))
        self.Continue_btn.setText(_translate("Elective_popupWindow_frm", "Continue"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Elective_popupWindow_frm = QtWidgets.QWidget()
    ui = Ui_Elective_popupWindow_frm()
    ui.setupUi(Elective_popupWindow_frm)
    Elective_popupWindow_frm.show()
    sys.exit(app.exec_())
