# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Project_Output_GUI_QT.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Output_window_frm(object):
    def setupUi(self, Output_window_frm):
        Output_window_frm.setObjectName("Output_window_frm")
        Output_window_frm.resize(665, 492)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 97))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 97))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 97))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 97))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Output_window_frm.setPalette(palette)
        self.ViewScheduler_lbl = QtWidgets.QLabel(Output_window_frm)
        self.ViewScheduler_lbl.setGeometry(QtCore.QRect(90, 10, 511, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.ViewScheduler_lbl.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ViewScheduler_lbl.setFont(font)
        self.ViewScheduler_lbl.setObjectName("ViewScheduler_lbl")
        self.SchedulerOutput_txtbx = QtWidgets.QTextBrowser(Output_window_frm)
        self.SchedulerOutput_txtbx.setGeometry(QtCore.QRect(90, 50, 471, 271))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.SchedulerOutput_txtbx.setFont(font)
        self.SchedulerOutput_txtbx.setObjectName("SchedulerOutput_txtbx")
        self.Return_btn = QtWidgets.QPushButton(Output_window_frm)
        self.Return_btn.setGeometry(QtCore.QRect(10, 440, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Return_btn.setFont(font)
        self.Return_btn.setObjectName("Return_btn")
        self.Print_btn = QtWidgets.QPushButton(Output_window_frm)
        self.Print_btn.setGeometry(QtCore.QRect(530, 440, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Print_btn.setFont(font)
        self.Print_btn.setObjectName("Print_btn")
        self.CheckSchedule_btn = QtWidgets.QPushButton(Output_window_frm)
        self.CheckSchedule_btn.setGeometry(QtCore.QRect(220, 330, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.CheckSchedule_btn.setFont(font)
        self.CheckSchedule_btn.setObjectName("CheckSchedule_btn")

        self.retranslateUi(Output_window_frm)
        QtCore.QMetaObject.connectSlotsByName(Output_window_frm)

    def retranslateUi(self, Output_window_frm):
        _translate = QtCore.QCoreApplication.translate
        Output_window_frm.setWindowTitle(_translate("Output_window_frm", "Class Scheduler Application"))
        self.ViewScheduler_lbl.setText(_translate("Output_window_frm", "AutoGenerated Schedule for Student"))
        self.Return_btn.setText(_translate("Output_window_frm", "Return to Main Menu"))
        self.Print_btn.setText(_translate("Output_window_frm", "Print Schedule"))
        self.CheckSchedule_btn.setText(_translate("Output_window_frm", "Check for Prerequiste Errors"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Output_window_frm = QtWidgets.QWidget()
    ui = Ui_Output_window_frm()
    ui.setupUi(Output_window_frm)
    Output_window_frm.show()
    sys.exit(app.exec_())
